version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password1" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  app:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    env_file: .env.development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./:/app/"
    ports:
      - "5238:80"
    working_dir: /app
    command: "/app/scripts/start.sh"