version: "3.9"
services:
  project-python-be-and-fe:
    build:
      context: app-python-django
    env_file: app-python-django/.env.development
    ports:
      - "8000:8000"

  product-javascript-be:
    build:
      context: app-javascript-nextjs
    env_file: app-javascript-nextjs/.env.development
    ports:
      - "3000:3000"

  product-csharp-be-and-fe:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    env_file: app-aspnet/.env.development
    depends_on:
      db-sqlserver:
        condition: service_healthy
    volumes:
      - "./app-aspnet/:/app/"
    ports:
      - "5238:80"
    working_dir: /app
    command: "/app/scripts/start.sh"

  db-sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password1" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
