version: "3.9"
services:
  project-python-be-and-fe:
    build:
      context: app-python-django
    env_file: app-python-django/.env.development
    ports:
      - "8000:8000"
  product-javascript-be:
    depends_on:
      unleash:
        condition: service_healthy
    build:
      context: app-javascript-nextjs
    env_file: app-javascript-nextjs/.env.development
    ports:
      - "3000:3000"
