version: "3.9"

services:
  web-feature-toggle:
    # https://docs.getunleash.io/reference/deploy/getting-started#option-one---use-docker
    image: unleashorg/unleash-server:4.22.5
    ports:
      - "4242:4242"
    environment:
      # https://github.com/Unleash/unleash/blob/417b56913a25cbeb91effb695777f52daea659cd/src/lib/create-config.ts#L120-L148
      DATABASE_URL: "postgres://unleash:jasmine@db/development"
      DATABASE_SSL: "false"
      LOG_LEVEL: "info"
      # https://docs.getunleash.io/reference/deploy/configuring-unleash#further-customization
      # Proxy clients must use one of these keys to connect to the
      # Proxy. To add more keys, separate them with a comma (`key1,key2`).
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      # Initialize Unleash with a default set of client API tokens. To
      # initialize Unleash with multiple tokens, separate them with a
      # comma (`token1,token2`).
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
    depends_on:
      db:
        condition: service_healthy
    command: [ "node", "index.js" ]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "development"
      POSTGRES_USER: "unleash"
      POSTGRES_PASSWORD: "jasmine"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--dbname=development",
          "--username=unleash"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
